### ISSUE TITLE
new Gazebo cannot broadcast joint state to rviz

### ISSUE THREAD

**Issue by ryanyu512** [automaticaddison/mycobot_ros2#1]
Hi,

Thanks for your friendly tutorial. 

I have directly downloaded this repository for learning and find that robot arm pose cannot be correctly shown in rviz and guess that new Gazebo is no longer able to publish joint states to rviz for correct visualisation based on your setting. 

I have changed ignition::gazebo and ignition-gazebo to gz::sim and gz-sim respectively. 

    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link1_to_link2</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link2_to_link3</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link3_to_link4</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link4_to_link5</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link5_to_link6</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>link6_to_link6flange</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_controller</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_base_to_gripper_left2</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_left3_to_gripper_left1</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_base_to_gripper_right3</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_base_to_gripper_right2</joint_name>
        </plugin>    
    </gazebo>  
    <gazebo>
        <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
            <joint_name>gripper_right3_to_gripper_right1</joint_name>
        </plugin>    
    </gazebo>    

And, I have also added the following section into mycobot_280_gazebo.urdf.xacro. I am not sure if you have missed something in this section since I find that this section is different when comparing mycobot_280_gazebo.urdf.xacro with mycobot_280_classic_gazebo.urdf.xacro.

    <gazebo>
        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic> 
            
    	    <joint_name>link1_to_link2</joint_name>      
    	    <joint_name>link2_to_link3</joint_name>
    	    <joint_name>link3_to_link4</joint_name>
    	    <joint_name>link4_to_link5</joint_name>
    	    <joint_name>link5_to_link6</joint_name>
    	    <joint_name>link6_to_link6flange</joint_name>
    	    <joint_name>gripper_controller</joint_name>
    	    <joint_name>gripper_base_to_gripper_left2</joint_name>
    	    <joint_name>gripper_left3_to_gripper_left1</joint_name>
            <joint_name>gripper_base_to_gripper_right3</joint_name>
            <joint_name>gripper_base_to_gripper_right2</joint_name>
    	    <joint_name>gripper_right3_to_gripper_right1</joint_name>
        </plugin>    
    </gazebo> 

Unfortunately, I still cannot fix this issue. Any advice would be highly appreciated. Anyway, the classic gazebo can work perfectly with rviz based on your current setting. 

Result: 
![Screenshot from 2024-05-20 03-08-06](https://github.com/automaticaddison/mycobot_ros2/assets/19774686/645e7314-d78b-4b87-a2fe-d72e96c92706)

Config: 
ROS version: ROS2 iron
OS: Ubuntu 22.04

**Comment by Casey1129** [comment]
Hi, are you able to resole this issue?

**Comment by automaticaddison** [comment]
@Casey1129 @ryanyu512 Assuming you have ROS 2 Iron:

Clone this repository into your ROS 2 workspace:

cd ~/ros2_ws/src
git clone https://github.com/automaticaddison/mycobot_ros2.git

Download any dependencies:
cd ~/ros2_ws/
rosdep install --from-paths src --ignore-src -r -y

Build your workspace
colcon build
source install/setup.bash

Launch the robot:
ros2 launch mycobot_gazebo mycobot_280_arduino_bringup_ros2_control_gazebo.launch.py

Make sure in RViz, you set the Fixed Frame to "world" under "Global Options". That may be causing your error
